### ISSUE TITLE
Auto-connect and auto-reconnect

### ISSUE THREAD

**Issue by FromZeus** [qbeon/webwire-go#11]
Make the webwire client automatically connect to the server right after initialization and make it optionally automatically reconnect on connection loss

**Comment by romshark** [comment]
That's a valid point, indeed it'd be better if the client takes care of connect/reconnect to ease the use of the library, though before this feature can be implemented the following questions must be clarified:

- **A**: When sending a signal when the server is being unresponsive, what shall we expect?
  - **A1**: blocking the calling goroutine until the connection is established and the signal is sent?
  - **A2**: same as A1 but timing out after a while returning a special `TimeoutConnErr`?
  - **A3**: immediately returning a `DisconnectedErr`?

- **B**: When making a request when the server is being unresponsive, what shall we expect?
  - **B1**: blocking the calling goroutine until the connection is established and the request is sent timing out when the specified (or default) request timeout is reached returning a special `TimeoutConnErr` instead of the regular `RequestTimeoutErr`?
  - **B2**: immediately returning a `DisconnectedErr`?

**Comment by romshark** [comment]
# Code Examples

## Signals

### A1
Make `Signal` automatically reconnect
```go
// NotifyEvent will block until the server is notified
func NotifyEvent() err {
  for {
    // Will block for as long as the server is unavailable
    err := client.Signal("newpost", ...);
    switch err := err.(type) {
	case nil:
      // Signal sent, exit function
      return
    default:
      // Unexpected failure
      panic(err)
    }
  }
}
```
User code loses control and blocks until the server receives the signal.

### A2
// Set during client initialization:
Options {
  DefaultSignalTimeout: 2 * time.Second,
}

Make `Signal` automatically reconnect with a timeout
```go
// NotifyEvent will block until the server is notified
func NotifyEvent() err {
  for {
    // Will block for as long as the server is unavailable
    err := client.Signal("newpost", ...);
    switch err := err.(type) {
	case nil:
      // Signal sent, exit function
      return
    DisconnectedErr:
      // 2 seconds reconnection timeout reached, retry sending
      continue
    default:
      // Unexpected failure
      panic(err)
    }
  }
}
```
User code gains control every 2 seconds until the server receives the signal. Will have behave same as **A1** if `DefaultSignalTimeout` is set to zero.

### Signal (A3)
Make `Signal` return an error immediately
```go
// NotifyEvent will block until the post was created
func NotifyEvent() err {
  for {
    err := client.Signal("newpost", ...);
    switch err := err.(type) {
	case nil:
      // Signal sent, exit function
      return
	case DisconnectedErr:
      // Will block until connected
      client.Connect()
      // Now retry sending when connected again
    default:
      // Unexpected failure
      panic(err)
    }
  }
}
```
It's quite okay, though you **must** remember to call `client.Connect()` to reconnect before retrying in case of a `DisconnectedErr`, otherwise CPU usage is dramatically increased iterating over the loop for thousands of times without any sleeps.


### Request (B1)
Make `Request` automatically reconnect
```go
// Set during client initialization:
Options {
  // don't ever timeout requests
  DefaultRequestTimeout: 0,
}

// CreatePost will block until the post was created
func CreatePost(title, text string) err {
  for {
    // Will block for as long as the server is unavailable
    reply, err := client.Request("newpost", ...);
    switch err := err.(type) {
	case nil:
      // Request processed, exit function
      return reply
    case ReqTimeoutErr:
      // If timed out then retry automatically trying to reconnect
      // though it'll only be called if DefaultRequestTimeout is bigger 0
      continue
    default:
      // Unexpected failure
      panic(err)
    }
  }
}
```
The only risk here, is that `client.Request` will block for as long as the server is unavailable if `DefaultRequestTimeout` is set to zero. One could mitigate that calling `client.TimedRequest(..., 10 * time.Second)` instead, then `ReqTimeoutErr` will be returned and the user code is back in control again.

### Request (B2)
Make `Request` return an error immediately
```go
// CreatePost will block until the post was created
func CreatePost(title, text string) err {
  for {
    reply, err := client.Request("newpost", ...);
    switch err := err.(type) {
	case nil:
      // Request processed, exit function
      return reply
    case ReqTimeoutErr:
      // Retry request
      continue
	case DisconnectedErr:
      // Will block until connected
      client.Connect()
      // Now retry sending when connected again
    default:
      // Unexpected failure
      panic(err)
    }
  }
}
```
Same as with **A3**, you **must** remember to call `client.Connect()` to reconnect before retrying the request in case of a `DisconnectedErr`, otherwise CPU usage is increased dramatically iterating over the loop for thousands of times without any sleeps.

## Conclusion

**Comment by FromZeus** [comment]
That's how I can see this:
* In case of Requests we can do it more reliable way by adding auto-reconnect functionality to them and use it like B1.
* In case of Signals I would recommend to let it be as it is due the nature of signals in "sent and forgot" way. So it's A3.

**Comment by romshark** [comment]
Having though about it, I think it's worth having `client.Request` try to autoconnect until timeout by default. If one sets `DefaultRequestTimeout` to 60 seconds for example and the server is unreachable, then it will try to connect within those 60 seconds before failing with a timeout error.

This feature should be optional but enabled by default, thus having an option to disable autoconnect is desirable. If autoconnect is disabled then `client.Request` should return a `DisconnectedErr` right away if the server isn't available.

I agree that `client.Signal` on the other hand should not support autoconnect, but it still should try to create a connection if there's none. If it fails to connect then it should return `DisconnectedErr` right away.

**Comment by romshark** [comment]
As of [commit #e996bb6](https://github.com/qbeon/webwire-go/commit/e996bb6dadafafa039b70345667be9886c0da2a2) the autoconnect feature is fully implemented and tested!

`client.Request`, `client.TimedRequest`, `client.RestoreSession` and `client.Signal` API methods will now automatically try (at least once) to connect to the server if there's no active connection and restore the session if necessary.

If `Options.Autoconnect` is enabled (which it is by default) then `client.Request`, `client.TimedRequest` and `client.RestoreSession` will try to automatically establish a connection to the server, even if the server is unavailable, for as long as the timeout isn't triggered, rather than returning a `DisconnectedErr` right away.

`client.Signal` is the only exception to autoconnect and will return a `DisconnectedErr` immediately if the server is unavailable.

Manually calling `client.Connect` is no longer required but remains available in the client API for special use cases, such as when one would want to test server connectivity and similar.
