### ISSUE TITLE
Unsynchronized session getter

### ISSUE THREAD

**Issue by FromZeus** [qbeon/webwire-go#18]
The client agent method `client.Session()` should return a copy of the session object though there is a problem with it returning a shallow copy of the session info map. This could lead to unsychronized access to the session info map as both session objects reference the same info object but can be owned by different goroutines.

**Comment by romshark** [comment]
As of [commit #2b6da64](https://github.com/qbeon/webwire-go/commit/2b6da6470b95dbe2aa7a5d4877d2768b450f3f2f) all session operations are now data race save.

Both, the client agent API and the API of the client implementation now return deep copies of session objects and session object field values. Users can now define their own session info object types and parsers respectively implementing the new `webwire.SessionInfo` interface. A default generic session info object is used, when no specific session info object parser is defined.

The only downside to using the default generic session info implementation instead of implementing your own is that complex field types (basically everything except `string` and `float64`) will be returned by methods such as `client.SessionInfo("fieldname")` as abstract types (like `[]interface{}` in case of a `[]string` for example).

Implementing the `webwire.SessionInfo` interface must be done carefully, any shallow copy returned could end up in race conditions and undefined behavior in case of concurrent session operations.
