### ISSUE TITLE
Support for concurrent message processing

### ISSUE THREAD

**Issue by FromZeus** [qbeon/webwire-go#23]
Currently the server does handle multiple connections concurrently but it processes the messages sequentially. Requests and signals of a single client are always processed in the goroutine handling that particular client, this could turn out critical, because even if we spawn goroutines manually in the `OnRequest` handler for example - we'd still block other requests when waiting for the blocking one to return a response. It'd therefore make sense to move the processing of messages into separate goroutines and ideally make this feature optional by providing a server option for disabling concurrent message processing.

**Comment by romshark** [comment]
As of [commit #d6105e9](https://github.com/qbeon/webwire-go/commit/d6105e9cb6d15530a969eb414379be2088e93218) messages are parsed and handled concurrently and throttled at a configured maximum number.

The server options now provide a new option: `MaxSessionConnections` which disables throttling when set to `0` and otherwise throttles the number of concurrently executed handlers to the specified maximum number.
