### ISSUE TITLE
Limit concurrency per client

### ISSUE THREAD

**Issue by FromZeus** [qbeon/webwire-go#25]
As of #23 the maximum number of concurrently executed handlers can be limited globally affecting all connected clients, though it might make sense to also allow limiting the number of concurrently executed handlers per client as well.

**Comment by romshark** [comment]
It does make sense, but I'm not yet sure, how to implement it, because there's three options:
- Setting the limit globally at server initialization affecting all clients.
- Setting the limit individually for each client during connection establishment.
- Setting a default global limit at server intialization, which is overridable by individual limits set during connection establishment.

The third option seems to be the most advanced one, though I think this is easily implementable by the library user with the rather simple second option, I don't think there's a need for a global limit here.

**Comment by romshark** [comment]
The concurrency limit is now set in the `BeforeUpgrade` hook this way:
```go
func (srv *ServerImpl) BeforeUpgrade(
	resp http.ResponseWriter,
	req *http.Request,
) wwr.ConnectionOptions {
	// return wwr.AcceptConnection(wwr.UnlimitedConcurrency)
	return wwr.AcceptConnection(10) // max 10 concurrent handlers
}
```

The server option `MaxConcurrentHandlers` is no longer available. If you still want to limit the total number of concurrent handlers for the entire server you'll need to set appropriate per-client limits (say `10` for a total `10.000` maximum concurently executed handlers for 1.000 concurrent clients) and limit the number of clients by atomically counting the number of connected clients and rejecting or redirecting incoming connections in the `BeforeUpgrade` hook when the limit is reached.
