### ISSUE TITLE
Support multiple underlying websocket connections

### ISSUE THREAD

**Issue by FromZeus** [qbeon/webwire-go#31]
# Client Feature Request

## Proposed Behavior
The client should provide an option for multiple underlying connections to be used for potentially increased throughput and lower latencies in network environments with high packet loss. Messages should be distributed fan-out [round-robin](https://en.wikipedia.org/wiki/Round-robin_scheduling) on the available connections.
Ideally, the number of underlying connections should be dynamically adjustable.

## Actual Behavior
The webwire client currently utilizes just one single websocket connection. In network environments where packet loss is small having an HTTP/2-style multiplexed single TCP/IP connection (which the underlying WebSocket basically is) is ideal, though in network environments with high packet loss HTTP/1.1-style multiple individual TCP/IP connections should, in theory, provide better throughput and latency due to the [TCP congestion-avoidance algorithm](https://en.wikipedia.org/wiki/TCP_congestion_control), which could potentially cause artificial slowdowns resulting in unsaturated network usage, at the cost of memory usage and higher connection establishment latency.

## Proposed API
_To be discussed_

## Proposed Implementation
_To be discussed_

## Additional information
The server must also support this feature by providing an option of a maximum number of acceptable connections for a single client, though I'm not quite sure whether this is the case.

**Comment by romshark** [comment]
In theory - it's possible, but it needs to be thoroughly tested, measured and benchmarked to deduce any serious conclusions. I think this is a lower priority task for future releases and could theoretically be done without breaking changes to the client's API in `v2.x`.

On the server-side, no changes need to be made, because there's no way to identify what connection belongs to what anonymous client. The user could just as well connect multiple individual webwire clients to the server and perform requests in a round-robin fashion.

**Comment by romshark** [comment]
Closing this issue due to the client implementation being moved to [webwire-go-client](https://github.com/qbeon/webwire-go-client)
