### ISSUE TITLE
Default session storage

### ISSUE THREAD

**Issue by DanielSchark** [qbeon/webwire-go#8]
Currently sessions are silently disabled if one of the sessions related hooks is undefined which is rather unintuitive. Consider adding a default built-in session storage implementation to be used by default if all sessions related hooks are undefined. This would improve usability and help newcomers getting started faster.

**Comment by romshark** [comment]
A default session storage implementation would indeed improve usability and help newcomers.

If sessions related hooks are **all** undefined then the default session storage could be used instead of just disabling sessions entirely. Though if one or multiple, **but not all** hooks are then defined the server instance constructor should raise a panic indicating that it's missing certain hooks, so either you define your own sessions storage or the default one is used.

It'd probably need to be an in-memory file-backed storage (probably a [memory-mapped file](https://en.wikipedia.org/wiki/Memory-mapped_file)) to avoid any complex dependencies.

**Comment by romshark** [comment]
Having though about it a little I can clearly state that a memory-mapped file would be too difficult to implement consistently on different platforms and not really worth it as a default solution for beginners.

I think it'd be more convenient to just store sessions on the file system by default in the traditional file-per-session way where the name of the file represents the session identifier. On lookup a file named with the session id is looked up in the configured directory and checked for existence.

Large project supporting millions of concurrent sessions on multiple machines will require specific optimization and would be worth implementing the `OnSessionCreated`,  `OnSessionLookup` and `OnSessionClosed` hooks themselfs.

**Comment by romshark** [comment]
As of [commit #c5e515b](https://github.com/qbeon/webwire-go/commit/c5e515bbf83795720ab6ff6831617a1bb44bde1a) a default file-based storage implementation has been added which will be used by default, if no session manager is provided.
It creates a file with a *.wwrsess* extension for each opened session in the configured directory. During the restoration of a session the file is looked up by name using the session key, read and unmarshalled recreating the session object. To permanently delete a session it's enough to remove the according file.

The server API has changed, `OnSessionCreated`, `OnSessionLookup` and `OnSessionClosed` hooks have been moved to the abstract `SessionManager` interface and need to be implemented with a custom session manager type implementing the interface.

Besides that, session info is now of JSON-compatible `map[string]interface{}` type and the client agent API has changed, read/write access is now done through dedicated client agent method:
- `HasSession` - returns true if the user agent has a session assigned
- `SessionKey` - returns the session key string
- `SessionCreation` - returns the time of the sessions creation
- `SessionInfo` - retrieves a session info field by name
- `Session` - returns a shallow copy of the session object (session.Info won't be cloned)
